"""Documentation Writing command — generates and updates documentation based on YAML configuration."""

from __future__ import annotations

import datetime
import typer
from rich.console import Console
from rich.panel import Panel
from pathlib import Path
import yaml

from factory.adapters.gitlab_client import GitLabClient

console = Console()

DOCUMENTATION_TEMPLATE = """\
# {title}

*Generated by SoftwareTeamFabrik · {date}*

---

{content}

---

*Last updated: {date}*
"""


def load_documentation_config(config_path: str) -> dict:
    """Load the documentation configuration from YAML file."""
    try:
        with open(config_path, 'r') as f:
            config = yaml.safe_load(f)
        return config if config else {}
    except FileNotFoundError:
        console.print(f"[red]✗ Documentation config file not found: {config_path}[/red]")
        raise typer.Exit(1)
    except yaml.YAMLError as e:
        console.print(f"[red]✗ Invalid YAML in documentation config: {e}[/red]")
        raise typer.Exit(1)


def generate_documentation_page(config: dict, gl: GitLabClient) -> str:
    """Generate documentation content based on the configuration."""
    title = config.get('title', 'Documentation')
    content = config.get('content', '')
    date = datetime.date.today().isoformat()
    
    return DOCUMENTATION_TEMPLATE.format(
        title=title,
        content=content,
        date=date
    )


def cmd_document(
    config: str = typer.Option("config/documentation.yml", "--config", "-c", help="Path to documentation config YAML"),
    output: str = typer.Option("docs", "--output", "-o", help="Output directory for documentation files"),
    update_wiki: bool = typer.Option(False, "--update-wiki", help="Update GitLab wiki with documentation"),
) -> None:
    """Generate and update documentation based on YAML configuration."""

    console.print()
    console.rule(f"[bold cyan]SoftwareTeamFabrik — Documentation Writing[/bold cyan]")
    console.print()

    # Load documentation configuration
    doc_config = load_documentation_config(config)
    console.print(f"  [green]✓[/green] Documentation config loaded: {config}")

    # Generate documentation content
    doc_content = generate_documentation_page(doc_config, None)
    console.print(f"  [green]✓[/green] Documentation generated")

    # Create output directory if it doesn't exist
    output_path = Path(output)
    output_path.mkdir(parents=True, exist_ok=True)
    console.print(f"  [green]✓[/green] Output directory ensured: {output_path}")

    # Write documentation to file
    doc_title = doc_config.get('title', 'Documentation').replace(' ', '_')
    output_file = output_path / f"{doc_title}.md"
    with open(output_file, 'w') as f:
        f.write(doc_content)
    console.print(f"  [green]✓[/green] Documentation written to: {output_file}")

    # Optionally update GitLab wiki
    if update_wiki:
        gl = GitLabClient(config_path="config/factory.yml")
        connected, detail = gl.connect()
        if not connected:
            console.print(f"[red]✗ GitLab connection failed: {detail}[/red]")
            raise typer.Exit(1)

        project = gl.project
        wiki_slug = doc_config.get('wiki_slug', doc_title)
        wiki_title = doc_config.get('title', 'Documentation')

        # Check if wiki page already exists
        existing_slugs = {w.slug for w in project.wikis.list()}
        if wiki_slug in existing_slugs:
            wiki = project.wikis.get(wiki_slug)
            wiki.content = doc_content
            wiki.title = wiki_title
            wiki.save()
            console.print(f"  [green]✓[/green] Wiki page updated: {wiki_slug}")
        else:
            project.wikis.create({"title": wiki_title, "content": doc_content})
            console.print(f"  [green]✓[/green] Wiki page created: {wiki_slug}")

        wiki_url = f"{gl._url}/{gl.project_path}/-/wikis/{wiki_slug}"
        console.print(f"  [bold]Documentation page[/bold]  {wiki_url}")

    console.print()
    console.print(Panel(
        f"Documentation generated successfully.\n\n"
        f"Files created: {output_file}\n\n"
        f"To update GitLab wiki, use: --update-wiki flag",
        title="Documentation Complete",
        border_style="green",
    ))
    console.print()
