"""Sprint Review command — generates wiki page and advances sprint on approval."""

from __future__ import annotations

import datetime
from pathlib import Path
import typer
from rich.console import Console
from rich.panel import Panel

from factory.adapters.gitlab_client import GitLabClient
from factory.core.scrum import ScrumEngine
from factory.core.planner import TokenAwarePlanner, PlanningAlgorithm

console = Console()

REVIEW_TEMPLATE = """\
# Sprint {number} Review — {name}

*Generated by SoftwareTeamFabrik · {date}*

---

## Sprint Goal
{sprint_name}

## Summary

| Metric | Value |
|---|---|
| Duration | {duration_days} days ({start} → {end}) |
| Issues Closed | {closed} |
| Issues Open | {open} |
| Velocity | {velocity}% |

## Closed Issues

{closed_issues_list}

## Open / Carried Over

{open_issues_list}

## Stakeholder Feedback

*(Persistent area for stakeholder feedback. This section survives agent updates and is carried forward to the next sprint.)*

{stakeholder_feedback}

## Retrospective Notes

*(Stakeholder to fill in during Sprint Review ceremony)*

- **What went well:**
- **What could improve:**
- **Action items for next sprint:**

---

*Approve this sprint and launch Sprint {next_number} with:*
```
factory review --sprint {number} --approve
```
"""


PLANNING_TEMPLATE = """\
# Sprint {number} Planning

*Generated by SoftwareTeamFabrik · {date}*

---

## Stakeholder Feedback from Sprint {prev_number}

{stakeholder_feedback}

## Sprint Goal

*(To be defined during Sprint Planning ceremony)*

## Issues

*(To be populated during Sprint Planning ceremony)*

---

*Finalize this planning page with:*
```
factory plan --sprint {number}
```
"""


def extract_stakeholder_feedback(wiki_content: str) -> str:
    """Extract the stakeholder feedback section from a wiki page."""
    if "## Stakeholder Feedback" not in wiki_content:
        return ""
    lines = wiki_content.split("\n")
    feedback_start = None
    feedback_end = None
    for i, line in enumerate(lines):
        if line.strip() == "## Stakeholder Feedback":
            feedback_start = i + 1
        if feedback_start is not None and line.strip().startswith("##"):
            feedback_end = i
            break
    if feedback_start is not None:
        if feedback_end is not None:
            return "\n".join(lines[feedback_start:feedback_end])
        else:
            return "\n".join(lines[feedback_start:])
    return ""


def cmd_review(
    sprint: int = typer.Option(..., "--sprint", "-s", help="Sprint number to review"),
    approve: bool = typer.Option(False, "--approve", help="Approve sprint and advance to next"),
    plan_next: bool = typer.Option(
        False, "--plan-next", help="Create a token-aware sprint plan for the next sprint"
    ),
    config: str = typer.Option("config/factory.yml", "--config", "-c"),
) -> None:
    """Generate a Sprint Review wiki page, or approve it to advance to the next sprint."""

    console.print()
    console.rule(f"[bold cyan]SoftwareTeamFabrik — Sprint {sprint} Review[/bold cyan]")
    console.print()

    gl = GitLabClient(config_path=config)
    connected, detail = gl.connect()
    if not connected:
        console.print(f"[red]✗ GitLab connection failed: {detail}[/red]")
        raise typer.Exit(1)

    scrum = ScrumEngine(config_path=config)
    state = scrum.current

    if state.number != sprint:
        console.print(f"[red]✗ Current sprint is #{state.number}, not #{sprint}.[/red]")
        raise typer.Exit(1)

    project = gl.project
    all_issues = project.issues.list(all=True)
    closed = [i for i in project.issues.list(state="closed", all=True)]
    open_issues = [i for i in all_issues if i.state == "opened"]

    velocity = scrum.velocity(len(closed), len(closed) + len(open_issues))

    def fmt_issue_list(issues) -> str:
        if not issues:
            return "_None_"
        return "\n".join(f"- #{i.iid} {i.title}" for i in issues)

    # Retrieve existing stakeholder feedback from the wiki
    stakeholder_feedback = ""
    wiki_slug_canonical = f"Sprint-{sprint}-Review"
    existing_slugs = {w.slug for w in project.wikis.list()}
    if wiki_slug_canonical in existing_slugs:
        wiki = project.wikis.get(wiki_slug_canonical)
        stakeholder_feedback = extract_stakeholder_feedback(wiki.content)

    wiki_content = REVIEW_TEMPLATE.format(
        number=sprint,
        name=state.name,
        sprint_name=state.name,
        date=datetime.date.today().isoformat(),
        duration_days=state.duration_days,
        start=state.start_date.isoformat(),
        end=state.end_date.isoformat(),
        closed=len(closed),
        open=len(open_issues),
        velocity=velocity,
        closed_issues_list=fmt_issue_list(closed),
        open_issues_list=fmt_issue_list(open_issues),
        stakeholder_feedback=stakeholder_feedback if stakeholder_feedback else "_None_",
        next_number=sprint + 1,
    )

    wiki_title = f"Sprint {sprint} Review"

    if wiki_slug_canonical in existing_slugs:
        wiki = project.wikis.get(wiki_slug_canonical)
        wiki.content = wiki_content
        wiki.title = wiki_title
        wiki.save()
        console.print(f"  [green]✓[/green] Wiki page updated: {wiki_slug_canonical}")
    else:
        project.wikis.create({"title": wiki_title, "content": wiki_content})
        console.print(f"  [green]✓[/green] Wiki page created: {wiki_slug_canonical}")

    wiki_url = f"{gl._url}/{gl.project_path}/-/wikis/{wiki_slug_canonical}"
    console.print(f"  [bold]Review page[/bold]  {wiki_url}")

    if not approve:
        console.print()
        console.print(Panel(
            f"Review the wiki page, fill in the retrospective notes, then run:\n\n"
            f"  [bold cyan]factory review --sprint {sprint} --approve[/bold cyan]",
            title="Next Step",
            border_style="yellow",
        ))
        console.print()
        return

    # --- Approval flow ---
    console.print()
    console.print(f"  [yellow]Approving Sprint {sprint}…[/yellow]")

    # Close the milestone
    milestones = project.milestones.list(search=f"Sprint {sprint}")
    if milestones:
        ms = milestones[0]
        ms.state_event = "close"
        ms.save()
        console.print(f"  [green]✓[/green] Milestone 'Sprint {sprint}' closed")

    # Advance sprint counter in factory.yml
    scrum.advance()
    console.print(f"  [green]✓[/green] factory.yml advanced to Sprint {sprint + 1}")

    # Carry forward stakeholder feedback to the next sprint's planning
    if stakeholder_feedback and stakeholder_feedback != "_None_":
        next_sprint_wiki_slug = f"Sprint-{sprint + 1}-Planning"
        next_sprint_wiki_title = f"Sprint {sprint + 1} Planning"
        next_sprint_wiki_content = PLANNING_TEMPLATE.format(
            number=sprint + 1,
            prev_number=sprint,
            date=datetime.date.today().isoformat(),
            stakeholder_feedback=stakeholder_feedback,
        )
        existing_next_slugs = {w.slug for w in project.wikis.list()}
        if next_sprint_wiki_slug in existing_next_slugs:
            next_wiki = project.wikis.get(next_sprint_wiki_slug)
            next_wiki.content = next_sprint_wiki_content
            next_wiki.title = next_sprint_wiki_title
            next_wiki.save()
        else:
            project.wikis.create({"title": next_sprint_wiki_title, "content": next_sprint_wiki_content})
        console.print(f"  [green]✓[/green] Stakeholder feedback carried forward to Sprint {sprint + 1} Planning")

    # Create token-aware sprint plan if --plan-next is specified
    if plan_next:
        console.print()
        console.print(f"  [yellow]Creating token-aware plan for Sprint {sprint + 1}…[/yellow]")
        
        # Initialize planner for next sprint
        next_sprint_number = sprint + 1
        sprint_label_lower = f"sprint-{next_sprint_number}"
        plan_path = Path(config).parent / f"sprint-{next_sprint_number}-plan.yml"
        planner = TokenAwarePlanner(plan_path=plan_path)
        
        # Get issues for next sprint
        console.print(f"  [bold]Fetching issues for Sprint {next_sprint_number}…[/bold]")
        
        try:
            issues = []
            page = 1
            per_page = 100
            while True:
                batch = project.issues.list(
                    state='opened',
                    labels=[sprint_label_lower],
                    per_page=per_page,
                    page=page,
                )
                if not batch:
                    break
                for issue in batch:
                    # Determine agent based on labels
                    agent = "developer"  # Default agent
                    if any(label.lower() == "architecture" for label in issue.labels):
                        agent = "architect"
                    elif any(label.lower() == "reviewer" for label in issue.labels):
                        agent = "reviewer"
                    
                    issues.append({
                        'issue_iid': issue.iid,
                        'title': issue.title,
                        'labels': issue.labels,
                        'description': issue.description or '',
                        'agent': agent
                    })
                if len(batch) < per_page:
                    break
                page += 1

            console.print(f"  Found {len(issues)} issues for sprint {next_sprint_number}")
            
            if issues:
                # Use default budget and algorithm for planning
                effective_budget = 1_000_000
                planning_algorithm = PlanningAlgorithm("greedy")
                
                console.print(f"  [bold]Budget[/bold]      {effective_budget:,} tokens")
                console.print(f"  [bold]Algorithm[/bold]   {planning_algorithm.value}")
                console.print()
                
                with console.status("[yellow]Creating optimal plan…[/yellow]"):
                    plan = planner.create_plan(
                        sprint_number=f"sprint-{next_sprint_number}",
                        budget=effective_budget,
                        issues=issues,
                        algorithm=planning_algorithm,
                    )
                
                console.print(f"  [green]✓[/green] Sprint {next_sprint_number} plan created successfully!")
                console.print(f"  [dim]Plan saved to: {planner.plan_path}[/dim]")
            else:
                console.print(f"  [yellow]⚠ No issues found for Sprint {next_sprint_number} — no plan created.[/yellow]")
                
        except Exception as exc:
            console.print(f"  [red]✗ Failed to create plan: {exc}[/red]")

    console.print()
    console.print(f"  [bold green]Sprint {sprint + 1} is ready.[/bold green] "
                  f"Run [bold cyan]factory status[/bold cyan] to see the new sprint.")
    console.print()
