"""Update Wiki command — automatically updates wiki pages based on merge request changes."""

from __future__ import annotations

import datetime
import typer
from rich.console import Console
from rich.panel import Panel

from factory.adapters.gitlab_client import GitLabClient
from factory.core.scrum import ScrumEngine

console = Console()


WIKI_UPDATE_TEMPLATE = """\
# Merge Request Update — {date}

*Generated by SoftwareTeamFabrik · {date}*

---

## Merge Request Details

- **MR ID:** {mr_id}
- **Title:** {mr_title}
- **Author:** {author}
- **Source Branch:** {source_branch}
- **Target Branch:** {target_branch}
- **State:** {state}

## Changes Summary

{changes_summary}

## Files Changed

{files_changed}

## Documentation Updates

{documentation_updates}

## Breaking Changes

{breaking_changes}

---

*This update was automatically generated based on the merge request changes.*
"""


def analyze_mr_changes(mr):
    """Analyze the changes in a merge request and generate a summary.

    Handles both python-gitlab 2.x (dict return) and 3.x+ (object return) formats.
    """
    changes = mr.changes()

    # Normalize changes to dict format
    if hasattr(changes, 'get'):
        # Already a dict (python-gitlab 2.x)
        changes_dict = changes
    elif hasattr(changes, '_attrs'):
        # python-gitlab 3.x+ returns an object with _attrs
        changes_dict = changes._attrs
    else:
        # Fallback: try to convert to dict
        try:
            changes_dict = dict(changes)
        except (TypeError, ValueError):
            changes_dict = {}

    files_changed = []
    documentation_updates = []
    breaking_changes = []

    for change in changes_dict.get("changes", []):
        file_path = change.get("new_path", change.get("old_path", ""))
        files_changed.append(f"- {file_path}")

        # Check for documentation updates
        if any(ext in file_path.lower() for ext in [".md", ".rst", ".txt"]):
            documentation_updates.append(f"- {file_path}")

        # Check for breaking changes (simplified heuristic)
        if "breaking" in change.get("diff", "").lower() or "BREAKING" in change.get("diff", "").upper():
            breaking_changes.append(f"- {file_path}")

    changes_summary = f"This merge request includes {len(files_changed)} file(s) changed."

    files_changed_str = "\n".join(files_changed) if files_changed else "_None_"
    documentation_updates_str = "\n".join(documentation_updates) if documentation_updates else "_None_"
    breaking_changes_str = "\n".join(breaking_changes) if breaking_changes else "_None_"

    return changes_summary, files_changed_str, documentation_updates_str, breaking_changes_str


def cmd_update_wiki(
    mr_id: int = typer.Option(..., "--mr-id", "-m", help="Merge Request ID to process"),
    config: str = typer.Option("config/factory.yml", "--config", "-c"),
) -> None:
    """Update wiki pages based on merge request changes."""

    console.print()
    console.rule(f"[bold cyan]SoftwareTeamFabrik — Wiki Update for MR !{mr_id}[/bold cyan]")
    console.print()

    gl = GitLabClient(config_path=config)
    connected, detail = gl.connect()
    if not connected:
        console.print(f"[red]✗ GitLab connection failed: {detail}[/red]")
        raise typer.Exit(1)

    project = gl.project

    # Get the merge request
    try:
        mr = project.mergerequests.get(mr_id)
        console.print(f"  [green]✓[/green] Found MR !{mr_id}: {mr.title}")
    except Exception as e:
        console.print(f"[red]✗ Failed to get MR !{mr_id}: {e}[/red]")
        raise typer.Exit(1)

    # Analyze changes
    console.print(f"  [blue]Analyzing changes...[/blue]")
    changes_summary, files_changed, documentation_updates, breaking_changes = analyze_mr_changes(mr)
    console.print(f"  [green]✓[/green] Analysis complete")

    # Generate wiki content
    wiki_content = WIKI_UPDATE_TEMPLATE.format(
        date=datetime.date.today().isoformat(),
        mr_id=mr_id,
        mr_title=mr.title,
        author=mr.author.get("name", "Unknown"),
        source_branch=mr.source_branch,
        target_branch=mr.target_branch,
        state=mr.state,
        changes_summary=changes_summary,
        files_changed=files_changed,
        documentation_updates=documentation_updates,
        breaking_changes=breaking_changes,
    )

    # Create/update wiki page
    wiki_slug = f"MR-{mr_id}-Update"
    wiki_title = f"MR !{mr_id} Update"

    existing_slugs = {w.slug for w in project.wikis.list()}
    if wiki_slug in existing_slugs:
        wiki = project.wikis.get(wiki_slug)
        wiki.content = wiki_content
        wiki.title = wiki_title
        wiki.save()
        console.print(f"  [green]✓[/green] Wiki page updated: {wiki_slug}")
    else:
        project.wikis.create({"title": wiki_title, "content": wiki_content})
        console.print(f"  [green]✓[/green] Wiki page created: {wiki_slug}")

    wiki_url = f"{gl._url}/{gl.project_path}/-/wikis/{wiki_slug}"
    console.print(f"  [bold]Update page[/bold]  {wiki_url}")

    console.print()
    console.print(Panel(
        f"Wiki has been updated with changes from MR !{mr_id}.\n"
        f"Review the update at: {wiki_url}",
        title="Update Complete",
        border_style="green",
    ))
    console.print()